### ISSUE TITLE
Error in  tdapOptions()

### ISSUE THREAD

**Issue by cndaqiang** [charleslian/pyramids#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cndaqiang/MyTools/TDAP/py/module/pyramids/io/result.py", line 672, in getBands
    options = tdapOptions()
  File "/home/cndaqiang/MyTools/TDAP/py/module/pyramids/io/fdf.py", line 21, in __init__
    self.options    = self.readFdf(self.inputFile)
  File "/home/cndaqiang/MyTools/TDAP/py/module/pyramids/io/fdf.py", line 83, in readFdf
    if lineList[0] == '%block':
IndexError: list index out of range

**Comment by cndaqiang** [comment]
# Solution
```
dos2unix input.fdf
```
